name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'atr_utility/**'
      - 'scripts/**'
      - 'requirements.txt'
      - '.github/workflows/build-windows-exe.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build GUI EXE
        shell: pwsh
        run: |
          powershell -ExecutionPolicy Bypass -File scripts\build_exe.ps1

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: atr-studio-windows-exe
          path: |
            dist/Atr Zoe Utility.exe
